### ISSUE TITLE
No module named 'omrdatasettools.downloaders'

### ISSUE THREAD

**Issue by valerdi** [apacha/MusicObjectDetection#1]
Hello, I'm trying to download the data with 

python datasets/download_all_datasets.py --dataset_directory ./data

but I'm getting this error

Traceback (most recent call last):
  File "datasets/download_all_datasets.py", line 4, in <module>
    from omrdatasettools.downloaders.CvcMuscimaDatasetDownloader import CvcMuscimaDatasetDownloader, CvcMuscimaDataset
ModuleNotFoundError: No module named 'omrdatasettools.downloaders'

**Comment by apacha** [comment]
You are right, the download links do no longer work and the OmrDatasetTools have been updated as well. Will try to fix this asap. In case you are interested in all three datasets (downloading capitan dataset is disabled because the dataset owners didn't want to make the dataset publicly available yet), please write an e-mail to me.
