### ISSUE TITLE
ModuleNotFoundError: No module named 'MusicObjectDetection'

### ISSUE THREAD

**Issue by LuquesP** [apacha/MusicObjectDetection#3]
Hi 

Get the error when using  
python preprocessing/normalize_all_datasets.py --dataset_directory ./data

**Comment by pandya293** [comment]
facing same issue
did you get any solutions ?
<img width="872" alt="Screenshot 2020-09-14 at 11 54 31 AM" src="https://user-images.githubusercontent.com/199303/93050749-0dbe2280-f681-11ea-80df-162e3d88e159.png">

**Comment by apacha** [comment]
This error occurs because the project is structured into sub-directories and Python can't find files that are in other directories, unless explicitly added to the python path.

To simplify this and fix the error, please run `pip install -e .` in the root directory of this project. That should fix it.
BTW: You can find the same information here: https://github.com/apacha/MusicObjectDetection#installing-requirements
